### PR TITLE
Remove unused methods for folder import

### PR DESCRIPTION
**Pull request by dorcastan**
Addresses the leftover code issue raised in #113.

### CODE REVIEW

**Comment by TSAI-HSIAO-HAN** [comment]
Can I confirm with you that currently we just add the imports in the root folder?

**Comment by dorcastan** [comment]
> Can I confirm with you that currently we just add the imports in the root folder?

For each bookmark, we first check whether its folder `f` is in Mark (`model.hasFolder(f)`). 
* If the folder `f` is not in Mark, add the bookmark to ROOT. 
* If the folder `f` is in mark, add the bookmark to the folder `f`.

**Comment by Na-Nazhou** [comment]
I realised there might still be some issues. Currently if there is a corresponding folder with the same name in the existing mark, we will just add the bookmark to that folder right? But there might be case where the folder structure from the import file is `school-general` while the folder structure in existing Mark is `entertainment - social media - general`. For a bookmark with Folder 'general', we will still add that bookmark to the folder 'general' in existing Mark but in fact the two folder structures are very different.

**Comment by dorcastan** [comment]
Right, forgot about that. I think the ideal method would be to create a new folder for imported bookmarks, then deconflict any duplicate folder names. For example, we could append `_1` to the imported folder name, so if a folder `myFolder` already exists in Mark, the imported folder is named `myFolder_1`.

I'm going to close this PR as the `addFolders` methods will probably be used if/ when I get round to implementing the above (folder import).

**Pull request closed without merging**
