### PR TITLE
Update images for User guide

### PR DESCRIPTION
**Pull request by kxyoke**
Screenshots for autotag to reminder

### CODE REVIEW

**Comment by openorclose** [comment]
How come some of the pictures the size so different?

**Comment by kxyoke** [comment]
Same on my side though; are you referring to the reminders? (or maybe annotation cus I set the size last time in the adoc)

**Comment by openorclose** [comment]
> Same on my side though; are you referring to the reminders? (or maybe annotation cus I set the size last time in the adoc)

oh yeah for the reminders some of them quite small

image

**Comment by kxyoke** [comment]
ahh ok then is cus of the image resize in the command; the image itself is the same size.
Since we are going to modify the images for our own parts (right?), I think we can change the sizing accordingly

one thing though - images may need to be abit small to fit in the ppp

**Comment by openorclose** [comment]
oh yeah ok then, if people need to make it smaller then just edit the size

**Pull request merged**
